name: "Docs"

on:
  schedule:
    - cron: '0 0 * * *'

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache phpDocumentor build files
        id: phpdocumentor-cache
        uses: actions/cache@v4
        with:
          path: .phpdoc/cache
          key: ${{ runner.os }}-phpdocumentor-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpdocumentor-
      - name: Build with phpDocumentor
        run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --target docs --cache-folder .phpdoc/cache --template default
      - name: Publish to docs branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: docs
        env:
          BUILD_DIR: docs/
