name: "Tests"

on: [push, pull_request]

jobs:
  build:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.2', '8.3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          
      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Execute static analysis
        run: composer analyze

      - name: Check coding standards
        run: composer check
        
      - name: Run tests
        run: |
          mkdir -p build/logs
          composer test -- --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
